name: Firebase Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@master

      - name: 'Authenticate with GCP service account'
        uses: w9jds/firebase-action@v13.20.2
        env:
          GCP_SA_KEY: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Setup Node.js 20'
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 'Install dependencies'
        run: 'cd ./firebase/functions && npm i'

      - name: 'Deploy functions'
        uses: w9jds/firebase-action@v13.20.2
        with:
          args: 'deploy --only functions'
        env:
          GCP_SA_KEY: '${{ secrets.GCP_SA_KEY }}'
          PROJECT_PATH: './firebase'

      - name: 'Deploy firestore'
        uses: w9jds/firebase-action@v13.20.2
        with:
          args: 'deploy --only firestore --force'
        env:
          GCP_SA_KEY: '${{ secrets.GCP_SA_KEY }}'
          PROJECT_PATH: './firebase'
